substitutions:
  friendly_name: ESPHome Tesla BLE
  device_name: tesla-ble
  device_description:  Tesla BLE

esphome:
  name: ${device_name}
  name_add_mac_suffix: true
  friendly_name: ${friendly_name}
  comment: ${device_description}
  project:
    name: yoziru.esphome-tesla-ble
    version: "2024.7.28"
  libraries:
    - https://github.com/yoziru/tesla-ble.git#v2.2.0

packages:
  common: !include common.yml
  client: !include client.yml
  # listener: !include listener.yml # Uncomment this to scan find your VIN BLE MAC address

logger:
  level: INFO

api:
  encryption:
    key: !secret api_encryption_key

# sync time with home assistant
time:
  - platform: homeassistant
    id: homeassistant_time

ota:
  platform: esphome
  password: !secret ota_password


esp32_ble_tracker:
  scan_parameters:
    # Activate scan only after wifi connect, see https://github.com/esphome/issues/issues/2941#issuecomment-1842369092
    continuous: false

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    password: !secret wifi_hotspot_password
  # Activate scan only after wifi connect, see https://github.com/esphome/issues/issues/2941#issuecomment-1842369092
  on_connect:
    - esp32_ble_tracker.start_scan:
       continuous: true
  on_disconnect:
    - esp32_ble_tracker.stop_scan:

captive_portal:
